spring.application.name=lost-found

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/lost_found}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:your_password}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=${SERVER_PORT:8080}